import { calcXP } from './gamification.js'

export const SEED_WORKOUTS = [
  { date: '2026-04-25', type: 'mixed',   duration: 40,  exercises: ['Squats','Leg Press','Treadmill'],                          notes: 'Day 1 restart! 30 min legs + 10 min treadmill. Felt accomplished 💪', partner: null },
  { date: '2026-04-26', type: 'cardio',  duration: 30,  exercises: ['Treadmill','Cardio'],                                      notes: 'Treadmill and cardio', partner: null },
  { date: '2026-04-27', type: 'weights', duration: 40,  exercises: ['Bench Press','Rows'],                                      notes: 'Chest and rows, 40 mins', partner: null },
  { date: '2026-04-29', type: 'mixed',   duration: 45,  exercises: ['Treadmill','Kickouts','Pull-ups'],                         notes: 'Cardio bursts + legs + pull-ups 7-8 reps clean 💪', partner: null },
  { date: '2026-04-30', type: 'weights', duration: 50,  exercises: ['Bench Press','Shoulder Press','Triceps'],                  notes: 'Chest / shoulders / triceps with Hassan', partner: 'Hassan' },
  { date: '2026-05-02', type: 'cardio',  duration: 15,  exercises: ['Treadmill'],                                               notes: '15 mins cardio treadmill', partner: null },
  { date: '2026-05-03', type: 'mixed',   duration: 70,  exercises: ['Treadmill','Pull-ups','Dips'],                             notes: '70 mins light cardio + 5 mins assisted dips and pull-ups. Sore from arm/chest day.', partner: null },
  { date: '2026-05-05', type: 'mixed',   duration: 40,  exercises: ['Bench Press','Treadmill'],                                 notes: 'Bench press and treadmill, 40 mins', partner: null },
  { date: '2026-05-07', type: 'cardio',  duration: 30,  exercises: ['Running'],                                                 notes: '30 min run 🏃', partner: null },
  { date: '2026-05-09', type: 'mixed',   duration: 40,  exercises: ['Running','Squats','Bench Press'],                          notes: 'Day 10! 🎯 10 min jog + sprint + walk, 30 min weights', partner: null },
  { date: '2026-05-10', type: 'mixed',   duration: 20,  exercises: ['Treadmill','Bench Press','Chest Press'],                   notes: "Mother's Day 🌸 Alternating cardio + chest press, aiming to finish strong", partner: null },
  { date: '2026-05-12', type: 'weights', duration: 40,  exercises: ['Bicep Curls','Triceps'],                                   notes: 'Biceps and triceps in NYC 🗽', partner: null },
  { date: '2026-05-14', type: 'weights', duration: 30,  exercises: ['Squats','Shoulder Press'],                                 notes: 'Legs and shoulders, 30 mins', partner: null },
  { date: '2026-05-16', type: 'cardio',  duration: 10,  exercises: ['Jogging'],                                                 notes: '10 min jog, 2 loops around block 🏃', partner: null },
  { date: '2026-05-17', type: 'cardio',  duration: 10,  exercises: ['Jogging'],                                                 notes: '10 min jog, 2 loops around block', partner: null },
  { date: '2026-05-21', type: 'mixed',   duration: 37,  exercises: ['Treadmill','Bench Press','Squats'],                        notes: '7 min treadmill + 3 min run + 30 min bench & squat press', partner: null },
  { date: '2026-05-23', type: 'mixed',   duration: 15,  exercises: ['Push-ups','Kickouts','Yoga'],                              notes: 'Body weight: push-ups, glutes, kickouts, yoga. After work shift 🧘', partner: null },
  { date: '2026-05-24', type: 'mixed',   duration: 15,  exercises: ['Push-ups','Squats'],                                       notes: 'Another solid 10-15 min body weight session', partner: null },
  { date: '2026-05-25', type: 'mixed',   duration: 35,  exercises: ['Running','Push-ups'],                                      notes: '30 min run (40% walks) with Melike + 5 min pushups 🏃', partner: 'Melike' },
  { date: '2026-05-26', type: 'weights', duration: 45,  exercises: ['Bench Press','Leg Press','Squats','Pull-ups'],             notes: 'Day 20! 💪 Bench x2, leg press + squats, pull-ups x2. Pushed through feeling unwell.', partner: null },
  { date: '2026-05-31', type: 'cardio',  duration: 60,  exercises: ['Running','Walking'],                                       notes: '30 min run + 30 min walk at Downsview Park 🌳', partner: null },
  { date: '2026-06-01', type: 'weights', duration: 50,  exercises: ['Lat Pulldown','Bicep Curls','Triceps','Squats'],           notes: 'Lat pulldowns + bicep curls (30lb x6) + triceps (44lb x6), squats during rest', partner: null },
  { date: '2026-06-06', type: 'cardio',  duration: 40,  exercises: ['Running','Walking'],                                       notes: '30 min run + 10 min walk by Yorkdale / Orfus / Dufferin 🏙️', partner: null },
  { date: '2026-06-07', type: 'mixed',   duration: 100, exercises: ['Biking','Bench Press','Push-ups'],                         notes: 'Biked 1.5 hrs + 5 min weights and bodyweight. Good protein day 🚴', partner: null },
  { date: '2026-06-09', type: 'weights', duration: 100, exercises: ['Squats','Glute Machine','Walking'],                        notes: '40 min squats and glutes + 1 hr walk 🦵', partner: null },
  { date: '2026-06-12', type: 'weights', duration: 45,  exercises: ['Triceps','Bench Press','Pull-ups','Dips','Squats'],        notes: 'Triceps, bench, pull-ups, dips + alternating legs', partner: null },
  { date: '2026-06-16', type: 'weights', duration: 45,  exercises: ['Bench Press','Triceps','Squats','Glute Machine'],          notes: 'Bench barbell (40lb each) + dumbbells max, triceps x2, squats + glutes', partner: null },
  { date: '2026-06-17', type: 'weights', duration: 20,  exercises: ['Squats'],                                                  notes: 'Squats 40lb each + 5 min walk. Need to do more exercises!', partner: null },
  { date: '2026-06-23', type: 'weights', duration: 30,  exercises: ['Bench Press','Crunches'],                                  notes: 'Chest and abs with Mel 🏋️', partner: 'Melike' },
  { date: '2026-06-25', type: 'weights', duration: 25,  exercises: ['Squats','Hip Raises'],                                     notes: 'Fit4Less — squats and hip raises, 20-25 mins', partner: null },
  { date: '2026-06-27', type: 'weights', duration: 75,  exercises: ['Pull-ups','Treadmill','Bench Press','Squats','Abductors'], notes: 'Day 31! Assisted pull-ups (35lb) + treadmill 12min + bench (35lb x3) + squats (35lb x3) + abductors 100lb 💪', partner: null },
  { date: '2026-07-09', type: 'mixed',   duration: 25,  exercises: ['Treadmill','Deadlift'],                                    notes: 'Back after tough period 💫 15 min cardio + 10 min deadlift. Progress.', partner: null },
  { date: '2026-07-10', type: 'weights', duration: 45,  exercises: ['Squats','Bench Press','Triceps','Glute Machine'],          notes: 'Squats (40lb each) + bench (45lb each) + triceps (30lb) + glute machine 💪', partner: null },
  { date: '2026-07-11', type: 'weights', duration: 65,  exercises: ['Bench Press','Squats','Rows','Triceps'],                   notes: '1 hour weights with Melike 🏋️', partner: 'Melike' },
  { date: '2026-07-14', type: 'weights', duration: 40,  exercises: ['Glute Machine','Bench Press'],                             notes: 'Day 35! Barely slept but showed up — shocked myself. Glute machine + bench 💪', partner: null },
  { date: '2026-07-17', type: 'weights', duration: 60,  exercises: ['Bicep Curls','Rows','Pull-ups','Lat Pulldown'],            notes: 'Biceps and back with Hassan at Planet Fitness 💪', partner: 'Hassan' },
  { date: '2026-07-18', type: 'weights', duration: 60,  exercises: ['Bench Press','Squats','Rows'],                             notes: 'Workout with Hassan at Planet Fitness 🏋️', partner: 'Hassan' },
  { date: '2026-07-20', type: 'weights', duration: 90,  exercises: ['Bench Press','Triceps','Chest Press'],                     notes: 'Day 38! 1.5 hrs with Hassan. Chest (3-4 exercises) + triceps x2. French press 4 sets max 35lb/side.', partner: 'Hassan' },
  { date: '2026-07-21', type: 'cardio',  duration: 38,  exercises: ['Running'],                                                 notes: '5km run in 35-40 min with Alif, Ahmad, Ella 🏅', partner: 'Alif, Ahmad, Ella' },
  { date: '2026-07-27', type: 'weights', duration: 30,  exercises: ['Rows','Back Extension'],                                   notes: 'Back session 30 mins. Rows 99lb. Seated superman 25lb 💪', partner: null },
  { date: '2026-08-08', type: 'weights', duration: 75,  exercises: ['Sled Push','Sled Pull','Bench Press','Squats'],            notes: 'Day 41! Sled push + pulls with the guys. 1.25 hrs, 4 main exercises 💥', partner: 'Friends' },
  { date: '2026-08-20', type: 'weights', duration: 30,  exercises: ['Pull-ups','Bench Press','Squats'],                         notes: 'Day 42! Back after 2 weeks. Thank god. 12 am pump 🌙 pull-ups, bench, squats', partner: null },
  { date: '2026-08-21', type: 'mixed',   duration: 30,  exercises: ['Jogging','Pull-ups','Squats','Push-ups'],                  notes: '1 am pump 🌙 Light jog + pull-ups + back + squats + decline push-ups. Eat cleaner!', partner: null },
  { date: '2026-08-25', type: 'mixed',   duration: 80,  exercises: ['Push-ups','Running','Biking'],                             notes: 'Day 44! Push-ups + 10 min run + biked 13km 🚴', partner: null },
  { date: '2026-08-26', type: 'weights', duration: 55,  exercises: ['Rows','Triceps','Squats','Treadmill'],                     notes: 'Day 45! Back + triceps + squats + 15 min treadmill walk 💪', partner: null },
  { date: '2026-09-01', type: 'mixed',   duration: 32,  exercises: ['Treadmill','Chest Press','Kickouts','Pull-ups'],           notes: 'Day 46! 12 min cardio + chest press x4 (max 40lb barbell) + kickouts x4 + pull-ups x2', partner: null },
  { date: '2026-09-03', type: 'weights', duration: 20,  exercises: ['Bicep Curls','Rows'],                                      notes: 'Day 47! Bicep curls (30lb x5-6) + rows (85lb x6). With Hassan.', partner: 'Hassan' },
  { date: '2026-09-04', type: 'cardio',  duration: 15,  exercises: ['Jogging'],                                                 notes: 'Day 48! First week at new job 🎉 15 min jog — steady pace, barely stopped. Progress 🏃', partner: null },
  { date: '2026-09-10', type: 'weights', duration: 40,  exercises: ['Bench Press','Squats','Back Extension','Kickouts'],        notes: 'Day 49! Chest + legs + back extensions, 40 mins', partner: null },
  { date: '2026-09-11', type: 'weights', duration: 60,  exercises: ['Bench Press','Triceps','Chest Press'],                     notes: 'Day 50! ⭐ Halfway to Foundation! Chest and triceps with Hassan 💪', partner: 'Hassan' },
  { date: '2026-09-13', type: 'weights', duration: 45,  exercises: ['Pull-ups','Rows','Lat Pulldown'],                          notes: 'Day 51! Back day — pull-ups, rows, lat pulldowns, 3 sets each', partner: null },
].map((w, i) => ({ ...w, id: `seed-${i}`, dayNumber: i + 1, xp: calcXP(w) }))

export const SEED_WEIGHT = { '2026-04-25': 171.6 }
